[project]
name = 'Tokenized-Vendor-Management-Strategic-Sourcing-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.market-analysis]
path = 'contracts/market-analysis.clar'
clarity_version = 2
epoch = 2.5

[contracts.negotiation-coordination]
path = 'contracts/negotiation-coordination.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
